
server:
  port: 8081

spring:
  application:
    name: demo-oauth2-keycloak

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/usuario
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: java
            scope: openid

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO


management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
